### PR TITLE
zh-CN: Update on #104 UI & Langs Rework - p1

### PR DESCRIPTION
**Pull request by NightFurySL2001**
Update on #104 .

### CODE REVIEW

**Comment by NightFurySL2001** [comment]
Sorry, problem with the merged version at pull/104/commits/ee5050191349d217dc45909fff49f617e2988f30. There are many strings that are cherry-picked wrongly and further check on zh-CN translation is required. Some of the changes didn't even occur in the original submitted version. Tq.

**Comment by Greg-21** [comment]
Unfortunately it can be possible. After cherry-picking your commit I also had to resolve conflicts, as you can see above ("This branch has conflicts that must be resolved"), and I did it as fast as possible, so I could accidentally keep some of the old sentences instead of the new ones from your commit. The only things I did intentionally here was an addition of the missing dot in line `editor.game.field.gamedir` and the exclamation mark in line `general.notready`.

Also, when I was converting launcher lang files from branch `master` into the new schema, I did it to all of them, even for those already touched by SKmedix, and I wasn't doing it by hand. After that I fixed several stupid things like the "Information" title instead of "Required Restart" (issue #105) or accidental removal of "Help us translate" sentence. Then I updated by hand the strings that differed between the branch `master` and the `ui-rework`. Since you did your latest changes in a separate branch, I didn't include them in my work. So it is also possible that the wrong strings are from here, not from the cherry pick.

**Comment by Greg-21** [comment]
Unfortunately it can be possible. After cherry-picking your commit I also had to resolve conflicts, as you can see above ("This branch has conflicts that must be resolved"), and I did it as fast as possible, so I could accidentally keep some of the old sentences instead of the new ones from your commit (I'm sorry for that). The only things I did intentionally here was an addition of the missing dot in line `editor.game.field.gamedir` and the exclamation mark in line `general.notready`.

Also, when I was converting launcher lang files from branch `master` into the new schema, I did it to all of them, even for those already touched by SKmedix, and I wasn't doing it by hand. After that I fixed several stupid things like the "Information" title instead of "Required Restart" (issue #105) or accidental removal of "Help us translate" sentence. Then I updated by hand the strings that differed between the branch `master` and the `ui-rework`. Since you did your latest changes in a separate branch, I didn't include them in my work. So it is also possible that the wrong strings are from here, not from the cherry pick.

**Comment by NightFurySL2001** [comment]
Question: was it Java arguments or JVM arguments?
Also, the exclamation mark in `sidebar.game.button.play`, `sidebar.game.button.play.demo`, `sidebar.game.button.play.offline`  is removed whn commit. I think it is required at there due to no equivalent call-to-action verb available for "Play".
[P/S: anyone can teach me how to use GitHub? XD I only know the basics to contibuting, but not more.]

**Comment by NightFurySL2001** [comment]
Also just use this file: https://github.com/NightFurySL2001/SKlauncher/blob/patch-1/assets/launcher/lang/sklmessages_zh_CN.properties. I updated all of them to try and catch up the translations.

**Comment by Greg-21** [comment]
To be honest, I don't know which one is better: Java arguments or JVM arguments. Even Oracle names it in two ways. When you type "JVM arguments" in the most popular search engine, you get a lot more results related to Minecraft, than with "Java arguments" search, so for me "JVM arguments" would be better here.

Also if you think the words will sound better with exclamation marks, you can just add them :)

**Comment by Greg-21** [comment]
To be honest, I don't know which one is better: Java arguments or JVM arguments. Even Oracle names it in two ways. If you type "JVM arguments" in the most popular search engine, you get a lot more results related to Minecraft, than with "Java arguments" search, so for me "JVM arguments" would be better here.

Also if you think the words will sound better with exclamation marks, you can just add them :)

**Comment by Greg-21** [comment]
To be honest, I don't know which one is better: Java arguments or JVM arguments. Even Oracle names it in two ways. If you type "JVM arguments" in the most popular search engine, you get a lot more results related to Minecraft, than with "Java arguments" search, so for me "JVM arguments" would be better here.

Also, if you think the words will sound better with exclamation marks, you can just add them :)

**Comment by Greg-21** [comment]
To be honest, I don't know which one is better: Java arguments or JVM arguments. Even Oracle names it in two ways. If you type "JVM arguments" in the most popular search engine, you get a lot more results related to Minecraft, than with "Java arguments" search, so for me "JVM arguments" would be better here.

**Comment by NightFurySL2001** [comment]
Well the exclamation marks are in th file already... should I push it again?

**Comment by Greg-21** [comment]
Could you look into 6e0d24df15766d865904292b9698067838690287 to tell me whether everything is OK with the translation?

**Comment by NightFurySL2001** [comment]
That's OK. Good to go.

**Comment by Greg-21** [comment]
Do you think your translation is already ready to be merged into `ui-rework` branch, or you need more time to improve it?

**Comment by Greg-21** [comment]
@NightFurySL2001 Do you think your translation is already ready to be merged into ui-rework branch, or you need more time to improve it?

**Comment by NightFurySL2001** [comment]
I think `6e0d24df15766d865904292b9698067838690287` is OK to go. :+1: 
Future changes may occur depending on the real UI but for now it's OK and can be merged now.

**Comment by Greg-21** [comment]
Good. So from now you can see your changes in `ui-rework` branch. I'm leaving this pull request open, but if you want, you can close it.

**Comment by skmedix** [comment]
Note: I want to drop new update in next week, so it needs to be merged before Monday

**Pull request closed without merging**
