### PR TITLE
PT-BR Translation update.

### PR DESCRIPTION
**Pull request by TheusKhan**
Includes website pt_BR translation.
Some credits go to FriskNightGuard for the beginning of website translation. Thanks.

Resolves: #89.

### CODE REVIEW

**Comment by Greg-21** [comment]
Does it mean that I can easily close PR #88?

**Comment by Greg-21** [comment]
Does it mean I can easily close PR #88?

**Comment by Greg-21** [comment]
Does it mean I can easily close #88?

**Comment by TheusKhan** [comment]
Yeah, you can close it now. I reforked the repository, there's no issues. XD

**Comment by Greg-21** [comment]
Without having Git Bash (or one of programs based on Git) installed on your PC, reforking is actually the only possibility to get rid of those problems.

**Comment by Greg-21** [comment]
Without having Git Bash (or one of programs based on Git) installed on your PC, reforking is actually the only possibility to get rid of those problems.

**Pull request merged**
