### PR TITLE
Ortography and grammar changes

### PR DESCRIPTION
**Pull request by Dozerly**
It's now more appropiate.
Introduced the according unicode characters too.

I didn't change the original author, though.

### CODE REVIEW

**Comment by skmedix** [comment]
**Note:** `más` has wrong char code, should be `m\u00e1s`

**Comment by skmedix** [comment]
@atesin Can you review these changes?

**Comment by atesin** [comment]
no problem boss..  wait me a little

**Comment by atesin** [comment]
i dont know exactly what dozerly had changed ..  it seems he changes unaccented uppercases to accented ones what is ok, but also turn to lowercase many initial noun uppercase what is wrong, according RAE initial noun's letter should be uppercase

http://lema.rae.es/dpd/srv/search?id=BapzSnotjD6n0vZiTp#4

i dont know if he is watching this conversation but please he should revert noun's initial lowercases to uppercases

**Pull request merged**
