### PR TITLE
Create sklmessages_ar_SA.properties

### PR DESCRIPTION
**Pull request by mh-mazen**
Arabic translation for the server

### CODE REVIEW

**Comment by skmedix** [comment]
Does it require RTL?

**Comment by mh-mazen** [comment]
Yes Arabic IS RTL

**Comment by NightFurySL2001** [comment]
Could the GUI be flipped when changing to RTL language SKMedix?

**Comment by skmedix** [comment]
Unfortunately no, JavaFX does not support RTL and I need to do a lot of changes to implement my own layout direction for EVERY component used in SKL. That's the main reason why it's not merged yet.

**Comment by mh-mazen** [comment]
Sorry to hear that , if you need any further assistance in translation i am happy to help

**Pull request merged**
