### PR TITLE
Update sklmessages_es_ES.properties

### PR DESCRIPTION
**Pull request by craciu25yt**

### CODE REVIEW

**Review by Dinocraft1515YT — APPROVED** [review]
I aprove this traducction, I'm from Spain and I think this is fine, please apply this as soon as possible

**Comment by skmedix** [comment]
Looks like there was one `es_ES` translation made before this one, if you think it still needs changes, press rebase your branch

**Comment by Dinocraft1515YT** [comment]
> Looks like there was one `es_ES` translation made before this one, if you think it still needs changes, press rebase your branch

but here are some traductions that aren't at the launcher, I think Spanish people will agree this one

**Comment by craciu25yt** [comment]
oh, I didn't know that there was another pendent update for spanish. So idk

**Comment by skmedix** [comment]
@craciu25yt They are still new strings that needs translation, so feel free to rebase this PR!

**Comment by craciu25yt** [comment]
how do I rebase it

**Comment by skmedix** [comment]
If you don't know how to rebase, it will probably be easier to make a new PR

**Pull request closed without merging**
