### PR TITLE
Reorganize some strings in the lang files

### PR DESCRIPTION
**Pull request by Greg-21**
To keep them in similar order, in which they are used in the launcher.

P.S. I have also added strings (from original en-US lang file) that were missing. So translators don't have to worry about missing descriptions :)

P.P.S. As @TheusKhan rightly noticed, I have also removed "Contributors History", because I think doubling functionality is not a right thing. If someone wants to look into the translation history, he can just visit this repo on GitHub. Now the "Contributors History" only takes up to 4 lines, but when the 3.0 version of the launcher will become more popular, more people could want to make translations. I'm sorry I didn't write that at once.

### CODE REVIEW

**Comment by skmedix** [comment]
Thanks for your contribution! However, these changes should be also reviewed by rest of the translators, as it's not just a string reorganization.

**Comment by TheusKhan** [comment]
It's okay, but him only reorganized some strings, changing the positions from there to here and removed all the contributors history. I think this unnecessary.
I also updated the portuguese translation.

**Comment by skmedix** [comment]
@Greg-21 Could you resolve conflicts? I would like to merge this asap;)

**Comment by Greg-21** [comment]
@skmedix Nice! I'll do it. But I have no time today. I'll try tomorrow.

**Comment by Greg-21** [comment]
@skmedix Nice! I'll do it. But I have no time today. I'll try tomorrow.

And before I can resolve these conflicts, we must decide what should we do with ellipsis (look here: #29).

**Comment by Greg-21** [comment]
@skmedix Nice! I'll do it. But I have no time today. I'll try tomorrow.

And before I can resolve these conflicts, we must decide what should we do with ellipsis (look [here](https://github.com/skmedix/SKlauncher/pull/29/files/a630371dec7f12943970cf199a19dd815fb36fbc#diff-842014cd43077472604881f555621666)).

**Comment by skmedix** [comment]
Thanks a lot for your contribution! :tada:

**Pull request merged**
