### PR TITLE
Create webmessages_tr.properties - Turkish Translation

### PR DESCRIPTION
**Pull request by fightlord123**
Translated the website to Turkish language!

### CODE REVIEW

**Comment by skmedix** [comment]
Thank you! I don't know when we will merge it tho, we need to re-implement translations into our new site

**Comment by ToastcodeDev** [comment]
:v

**Comment by skmedix** [comment]
Sorry, we didn't re-implemeted i18n on our website, but it's still planned, don't worry!

**Comment by fightlord123** [comment]
Ok, no problem! I will update the translation with new strings if you add!

**Pull request merged**
